### ISSUE TITLE
make prepare creates s3am but it is not in the .gitignore

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/toil-lib#19]

**Comment by arkal** [comment]
Also venv and bin

**Comment by jvivian** [comment]
`make clean` deletes s3am and bin.  `venv` isn't created by the Makefile, but could be ignored if we changed the name to `.env` which mirrors the `jenkins.sh`.  I'll go ahead and do that.

**Comment by arkal** [comment]
I reopened this. I would add a note somewhere saying that you need to use .env vs venv. Coming to the s3am thing, i might want to push something to github without removing s3am. At the very least, add s3am/ to the .gitignore

**Comment by jvivian** [comment]
`make clean` removes s3am.

**Comment by hannes-ucsc** [comment]
I agree with adding `/s3am/` to the .gitignore file. Note the slashes before and after.

**Comment by hannes-ucsc** [comment]
Disagree about documenting `.env`. I see no mention of it except in `jenkins.sh` so the user should be free to chose whatever name for the virtualenv.

**Comment by hannes-ucsc** [comment]
Two tacos (plus the one burrito I already owe) go to @cket for catching the ball that was bouncing back and forth between these two ;-)
