### ISSUE TITLE
`make pypi` fails on jenkins

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/toil-lib#27]
+ python2.7 setup.py egg_info --tag-build=.dev50 sdist bdist_egg upload
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    toil_version = check_provided('toil', min_version='3.3.0', max_version='3.5.0')
  File "setup.py", line 45, in check_provided
    raise RuntimeError(' '.join(messages))
RuntimeError: Cannot find a valid installation of Toil. Installing Toil should fix this problem. Setup doesn't install Toil automatically to give you a chance to choose any of the optional extras that Toil provides. More on installing Toil at http://toil.readthedocs.io/en/latest/installation.html.
make: *** [pypi] Error 1
Build step 'Execute shell' marked build as failure
Recording test results

I inadvertently broke this in #26

**Comment by jvivian** [comment]
Wasn't this resolved in #28?

**Comment by cket** [comment]
Yes, this was resolved by #28, I referenced the wrong ticket number in the PR.
