### ISSUE TITLE
Support piped commands in docker_call

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/toil-lib#80]
toil-vg needs to be able to run things like vg ids -s graph.vg | vg mod -X 100 > output.graph, where vg can be a docker container.  

Am currently using https://github.com/cmarkello/toil-lib/commit/75c21593abb1c5856d5e4be01ef5c1018cc13104

This logic needs to get pushed up so we don't get too far out of sync.  Will make a cleaned up PR shortly.

**Comment by glennhickey** [comment]
I see that this function is duplicated in toil.  Looking at the issues, it seems that's where it should be.  Will PR this update into toil instead.

**Comment by jvivian** [comment]
@glennhickey — Do you want to close this and open a new issue against Toil?
